import {MigrationInterface, QueryRunner} from "typeorm";

export class User1600578564828 implements MigrationInterface {
    name = 'User1600578564828'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `collection` DROP FOREIGN KEY `collectionPlayerId_fk`");
        await queryRunner.query("ALTER TABLE `deck` DROP FOREIGN KEY `playerId_fk`");
        await queryRunner.query("ALTER TABLE `gamestate` DROP FOREIGN KEY `gameId_fk`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `player1Id_fk`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `player2Id_fk`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `winnerId_fk`");
        await queryRunner.query("ALTER TABLE `lobby` DROP FOREIGN KEY `lobby_game_fk`");
        await queryRunner.query("ALTER TABLE `lobby` DROP FOREIGN KEY `lobby_owner_fk`");
        await queryRunner.query("ALTER TABLE `pw_reset` DROP FOREIGN KEY `pw_reset_user`");
        await queryRunner.query("DROP INDEX `username_UNIQUE` ON `user`");
        await queryRunner.query("DROP INDEX `email_UNIQUE` ON `user`");
        await queryRunner.query("DROP INDEX `playerId_UNIQUE` ON `collection`");
        await queryRunner.query("DROP INDEX `playerId_fk_idx` ON `deck`");
        await queryRunner.query("DROP INDEX `gameId_UNIQUE` ON `gamestate`");
        await queryRunner.query("DROP INDEX `player1Id_fk_idx` ON `game`");
        await queryRunner.query("DROP INDEX `player2Id_fk_idx` ON `game`");
        await queryRunner.query("DROP INDEX `winnerId_fk_idx` ON `game`");
        await queryRunner.query("DROP INDEX `seat1Id_UNIQUE` ON `lobby`");
        await queryRunner.query("DROP INDEX `seat2Id_UNIQUE` ON `lobby`");
        await queryRunner.query("DROP INDEX `lobby_owner_fk_idx` ON `lobby`");
        await queryRunner.query("DROP INDEX `lobby_game_fk_idx` ON `lobby`");
        await queryRunner.query("DROP INDEX `userId_UNIQUE` ON `pw_reset`");
        await queryRunner.query("DROP INDEX `token_UNIQUE` ON `pw_reset`");
        await queryRunner.query("ALTER TABLE `user` ADD `profilePic` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `salt`");
        await queryRunner.query("ALTER TABLE `user` ADD `salt` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `role`");
        await queryRunner.query("ALTER TABLE `user` ADD `role` varchar(255) NOT NULL DEFAULT 'PLAYER'");
        await queryRunner.query("ALTER TABLE `user` CHANGE `created` `created` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `collection` DROP COLUMN `cards`");
        await queryRunner.query("ALTER TABLE `collection` ADD `cards` longtext NOT NULL");
        await queryRunner.query("ALTER TABLE `collection` CHANGE `playerId` `playerId` int NULL");
        await queryRunner.query("ALTER TABLE `collection` ADD UNIQUE INDEX `IDX_a9a00111ab551cb105465fce25` (`playerId`)");
        await queryRunner.query("ALTER TABLE `deck` DROP COLUMN `name`");
        await queryRunner.query("ALTER TABLE `deck` ADD `name` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `deck` CHANGE `cards` `cards` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `deck` CHANGE `face` `face` int NOT NULL");
        await queryRunner.query("ALTER TABLE `deck` CHANGE `playerId` `playerId` int NULL");
        await queryRunner.query("ALTER TABLE `deck` ADD UNIQUE INDEX `IDX_fcd3a7bc021f6846ffe6e6fbfb` (`playerId`)");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `turn` `turn` int NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `player1Board` `player1Board` varchar(255) NOT NULL DEFAULT '[]'");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `player2Board` `player2Board` varchar(255) NOT NULL DEFAULT '[]'");
        await queryRunner.query("ALTER TABLE `gamestate` DROP COLUMN `player1Discard`");
        await queryRunner.query("ALTER TABLE `gamestate` ADD `player1Discard` varchar(255) NOT NULL DEFAULT '[]'");
        await queryRunner.query("ALTER TABLE `gamestate` DROP COLUMN `player2Discard`");
        await queryRunner.query("ALTER TABLE `gamestate` ADD `player2Discard` varchar(255) NOT NULL DEFAULT '[]'");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `player1ShuffledDeck` `player1ShuffledDeck` varchar(255) NOT NULL DEFAULT '[]'");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `player2ShuffledDeck` `player2ShuffledDeck` varchar(255) NOT NULL DEFAULT '[]'");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `connectedPlayers` `connectedPlayers` int NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `gameId` `gameId` int NULL");
        await queryRunner.query("ALTER TABLE `gamestate` ADD UNIQUE INDEX `IDX_ff1f3ba7eb0bdd65c150a8ea1d` (`gameId`)");
        await queryRunner.query("ALTER TABLE `game` DROP COLUMN `color1`");
        await queryRunner.query("ALTER TABLE `game` ADD `color1` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `game` DROP COLUMN `color2`");
        await queryRunner.query("ALTER TABLE `game` ADD `color2` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `game` CHANGE `player1Id` `player1Id` int NULL");
        await queryRunner.query("ALTER TABLE `game` ADD UNIQUE INDEX `IDX_7b7f91302f66ab534423c96aa3` (`player1Id`)");
        await queryRunner.query("ALTER TABLE `game` ADD UNIQUE INDEX `IDX_3b85329cbe5b9f9002f05018fa` (`player2Id`)");
        await queryRunner.query("ALTER TABLE `game` CHANGE `player1DeckId` `player1DeckId` int NULL");
        await queryRunner.query("ALTER TABLE `game` ADD UNIQUE INDEX `IDX_7ffaab31f30d682b4e22a4a055` (`player1DeckId`)");
        await queryRunner.query("ALTER TABLE `game` ADD UNIQUE INDEX `IDX_08a696fb851dfa3f579e621c60` (`player2DeckId`)");
        await queryRunner.query("ALTER TABLE `game` ADD UNIQUE INDEX `IDX_cd57acb58d1147c23da5cd09ca` (`winnerId`)");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `name`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `name` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `created` `created` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `capacity` `capacity` int NOT NULL");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `connectedCount` `connectedCount` int NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `seat1Ready`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `seat1Ready` tinyint NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `seat2Ready`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `seat2Ready` tinyint NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `seatRule` `seatRule` int NOT NULL DEFAULT 0");
        await queryRunner.query("ALTER TABLE `lobby` ADD UNIQUE INDEX `IDX_9248271fd0074cad6e0dfd83f9` (`gameId`)");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `ownerId` `ownerId` int NULL");
        await queryRunner.query("ALTER TABLE `lobby` ADD UNIQUE INDEX `IDX_62cf2a65f7f4d65d65015e56d1` (`ownerId`)");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `seat1Id`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `seat1Id` int NULL");
        await queryRunner.query("ALTER TABLE `lobby` ADD UNIQUE INDEX `IDX_679afaf055e3e5d2b2f3ac14de` (`seat1Id`)");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `seat2Id`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `seat2Id` int NULL");
        await queryRunner.query("ALTER TABLE `lobby` ADD UNIQUE INDEX `IDX_427b7cf6b08e26308e2c815526` (`seat2Id`)");
        await queryRunner.query("ALTER TABLE `pw_reset` DROP COLUMN `token`");
        await queryRunner.query("ALTER TABLE `pw_reset` ADD `token` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `pw_reset` CHANGE `userId` `userId` int NULL");
        await queryRunner.query("ALTER TABLE `pw_reset` ADD UNIQUE INDEX `IDX_9c989fbbc6b7314dbca24cf49a` (`userId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_a9a00111ab551cb105465fce25` ON `collection` (`playerId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_fcd3a7bc021f6846ffe6e6fbfb` ON `deck` (`playerId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_ff1f3ba7eb0bdd65c150a8ea1d` ON `gamestate` (`gameId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_7b7f91302f66ab534423c96aa3` ON `game` (`player1Id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_3b85329cbe5b9f9002f05018fa` ON `game` (`player2Id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_7ffaab31f30d682b4e22a4a055` ON `game` (`player1DeckId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_08a696fb851dfa3f579e621c60` ON `game` (`player2DeckId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_cd57acb58d1147c23da5cd09ca` ON `game` (`winnerId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_9248271fd0074cad6e0dfd83f9` ON `lobby` (`gameId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_62cf2a65f7f4d65d65015e56d1` ON `lobby` (`ownerId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_679afaf055e3e5d2b2f3ac14de` ON `lobby` (`seat1Id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_427b7cf6b08e26308e2c815526` ON `lobby` (`seat2Id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `REL_9c989fbbc6b7314dbca24cf49a` ON `pw_reset` (`userId`)");
        await queryRunner.query("ALTER TABLE `collection` ADD CONSTRAINT `FK_a9a00111ab551cb105465fce254` FOREIGN KEY (`playerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `deck` ADD CONSTRAINT `FK_fcd3a7bc021f6846ffe6e6fbfb7` FOREIGN KEY (`playerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `gamestate` ADD CONSTRAINT `FK_ff1f3ba7eb0bdd65c150a8ea1d3` FOREIGN KEY (`gameId`) REFERENCES `game`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_7b7f91302f66ab534423c96aa34` FOREIGN KEY (`player1Id`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_3b85329cbe5b9f9002f05018faf` FOREIGN KEY (`player2Id`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_7ffaab31f30d682b4e22a4a055b` FOREIGN KEY (`player1DeckId`) REFERENCES `deck`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_08a696fb851dfa3f579e621c609` FOREIGN KEY (`player2DeckId`) REFERENCES `deck`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `FK_cd57acb58d1147c23da5cd09cae` FOREIGN KEY (`winnerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `lobby` ADD CONSTRAINT `FK_9248271fd0074cad6e0dfd83f9d` FOREIGN KEY (`gameId`) REFERENCES `game`(`id`) ON DELETE CASCADE ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `lobby` ADD CONSTRAINT `FK_62cf2a65f7f4d65d65015e56d15` FOREIGN KEY (`ownerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `lobby` ADD CONSTRAINT `FK_679afaf055e3e5d2b2f3ac14dec` FOREIGN KEY (`seat1Id`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `lobby` ADD CONSTRAINT `FK_427b7cf6b08e26308e2c8155261` FOREIGN KEY (`seat2Id`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `lobby` ADD CONSTRAINT `FK_48b53966e10d928dc4c2176d129` FOREIGN KEY (`seat1DeckId`) REFERENCES `deck`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `lobby` ADD CONSTRAINT `FK_27118cca0a1d88c1ce5d85f4e5b` FOREIGN KEY (`seat2DeckId`) REFERENCES `deck`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `pw_reset` ADD CONSTRAINT `FK_9c989fbbc6b7314dbca24cf49a2` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query("ALTER TABLE `pw_reset` DROP FOREIGN KEY `FK_9c989fbbc6b7314dbca24cf49a2`");
        await queryRunner.query("ALTER TABLE `lobby` DROP FOREIGN KEY `FK_27118cca0a1d88c1ce5d85f4e5b`");
        await queryRunner.query("ALTER TABLE `lobby` DROP FOREIGN KEY `FK_48b53966e10d928dc4c2176d129`");
        await queryRunner.query("ALTER TABLE `lobby` DROP FOREIGN KEY `FK_427b7cf6b08e26308e2c8155261`");
        await queryRunner.query("ALTER TABLE `lobby` DROP FOREIGN KEY `FK_679afaf055e3e5d2b2f3ac14dec`");
        await queryRunner.query("ALTER TABLE `lobby` DROP FOREIGN KEY `FK_62cf2a65f7f4d65d65015e56d15`");
        await queryRunner.query("ALTER TABLE `lobby` DROP FOREIGN KEY `FK_9248271fd0074cad6e0dfd83f9d`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_cd57acb58d1147c23da5cd09cae`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_08a696fb851dfa3f579e621c609`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_7ffaab31f30d682b4e22a4a055b`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_3b85329cbe5b9f9002f05018faf`");
        await queryRunner.query("ALTER TABLE `game` DROP FOREIGN KEY `FK_7b7f91302f66ab534423c96aa34`");
        await queryRunner.query("ALTER TABLE `gamestate` DROP FOREIGN KEY `FK_ff1f3ba7eb0bdd65c150a8ea1d3`");
        await queryRunner.query("ALTER TABLE `deck` DROP FOREIGN KEY `FK_fcd3a7bc021f6846ffe6e6fbfb7`");
        await queryRunner.query("ALTER TABLE `collection` DROP FOREIGN KEY `FK_a9a00111ab551cb105465fce254`");
        await queryRunner.query("DROP INDEX `REL_9c989fbbc6b7314dbca24cf49a` ON `pw_reset`");
        await queryRunner.query("DROP INDEX `REL_427b7cf6b08e26308e2c815526` ON `lobby`");
        await queryRunner.query("DROP INDEX `REL_679afaf055e3e5d2b2f3ac14de` ON `lobby`");
        await queryRunner.query("DROP INDEX `REL_62cf2a65f7f4d65d65015e56d1` ON `lobby`");
        await queryRunner.query("DROP INDEX `REL_9248271fd0074cad6e0dfd83f9` ON `lobby`");
        await queryRunner.query("DROP INDEX `REL_cd57acb58d1147c23da5cd09ca` ON `game`");
        await queryRunner.query("DROP INDEX `REL_08a696fb851dfa3f579e621c60` ON `game`");
        await queryRunner.query("DROP INDEX `REL_7ffaab31f30d682b4e22a4a055` ON `game`");
        await queryRunner.query("DROP INDEX `REL_3b85329cbe5b9f9002f05018fa` ON `game`");
        await queryRunner.query("DROP INDEX `REL_7b7f91302f66ab534423c96aa3` ON `game`");
        await queryRunner.query("DROP INDEX `REL_ff1f3ba7eb0bdd65c150a8ea1d` ON `gamestate`");
        await queryRunner.query("DROP INDEX `REL_fcd3a7bc021f6846ffe6e6fbfb` ON `deck`");
        await queryRunner.query("DROP INDEX `REL_a9a00111ab551cb105465fce25` ON `collection`");
        await queryRunner.query("ALTER TABLE `pw_reset` DROP INDEX `IDX_9c989fbbc6b7314dbca24cf49a`");
        await queryRunner.query("ALTER TABLE `pw_reset` CHANGE `userId` `userId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `pw_reset` DROP COLUMN `token`");
        await queryRunner.query("ALTER TABLE `pw_reset` ADD `token` varchar(45) NOT NULL");
        await queryRunner.query("ALTER TABLE `lobby` DROP INDEX `IDX_427b7cf6b08e26308e2c815526`");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `seat2Id`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `seat2Id` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `lobby` DROP INDEX `IDX_679afaf055e3e5d2b2f3ac14de`");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `seat1Id`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `seat1Id` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `lobby` DROP INDEX `IDX_62cf2a65f7f4d65d65015e56d1`");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `ownerId` `ownerId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `lobby` DROP INDEX `IDX_9248271fd0074cad6e0dfd83f9`");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `seatRule` `seatRule` int NULL DEFAULT '1'");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `seat2Ready`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `seat2Ready` int NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `seat1Ready`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `seat1Ready` int NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `connectedCount` `connectedCount` int NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `capacity` `capacity` int NULL DEFAULT '2'");
        await queryRunner.query("ALTER TABLE `lobby` CHANGE `created` `created` datetime(0) NULL DEFAULT CURRENT_TIMESTAMP");
        await queryRunner.query("ALTER TABLE `lobby` DROP COLUMN `name`");
        await queryRunner.query("ALTER TABLE `lobby` ADD `name` varchar(50) NOT NULL");
        await queryRunner.query("ALTER TABLE `game` DROP INDEX `IDX_cd57acb58d1147c23da5cd09ca`");
        await queryRunner.query("ALTER TABLE `game` DROP INDEX `IDX_08a696fb851dfa3f579e621c60`");
        await queryRunner.query("ALTER TABLE `game` DROP INDEX `IDX_7ffaab31f30d682b4e22a4a055`");
        await queryRunner.query("ALTER TABLE `game` CHANGE `player1DeckId` `player1DeckId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `game` DROP INDEX `IDX_3b85329cbe5b9f9002f05018fa`");
        await queryRunner.query("ALTER TABLE `game` DROP INDEX `IDX_7b7f91302f66ab534423c96aa3`");
        await queryRunner.query("ALTER TABLE `game` CHANGE `player1Id` `player1Id` int NOT NULL");
        await queryRunner.query("ALTER TABLE `game` DROP COLUMN `color2`");
        await queryRunner.query("ALTER TABLE `game` ADD `color2` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `game` DROP COLUMN `color1`");
        await queryRunner.query("ALTER TABLE `game` ADD `color1` varchar(45) NOT NULL");
        await queryRunner.query("ALTER TABLE `gamestate` DROP INDEX `IDX_ff1f3ba7eb0bdd65c150a8ea1d`");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `gameId` `gameId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `connectedPlayers` `connectedPlayers` int NULL DEFAULT '0'");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `player2ShuffledDeck` `player2ShuffledDeck` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `player1ShuffledDeck` `player1ShuffledDeck` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `gamestate` DROP COLUMN `player2Discard`");
        await queryRunner.query("ALTER TABLE `gamestate` ADD `player2Discard` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `gamestate` DROP COLUMN `player1Discard`");
        await queryRunner.query("ALTER TABLE `gamestate` ADD `player1Discard` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `player2Board` `player2Board` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `player1Board` `player1Board` varchar(255) NOT NULL");
        await queryRunner.query("ALTER TABLE `gamestate` CHANGE `turn` `turn` int NOT NULL");
        await queryRunner.query("ALTER TABLE `deck` DROP INDEX `IDX_fcd3a7bc021f6846ffe6e6fbfb`");
        await queryRunner.query("ALTER TABLE `deck` CHANGE `playerId` `playerId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `deck` CHANGE `face` `face` int NULL");
        await queryRunner.query("ALTER TABLE `deck` CHANGE `cards` `cards` varchar(255) NULL");
        await queryRunner.query("ALTER TABLE `deck` DROP COLUMN `name`");
        await queryRunner.query("ALTER TABLE `deck` ADD `name` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `collection` DROP INDEX `IDX_a9a00111ab551cb105465fce25`");
        await queryRunner.query("ALTER TABLE `collection` CHANGE `playerId` `playerId` int NOT NULL");
        await queryRunner.query("ALTER TABLE `collection` DROP COLUMN `cards`");
        await queryRunner.query("ALTER TABLE `collection` ADD `cards` mediumtext NOT NULL");
        await queryRunner.query("ALTER TABLE `user` CHANGE `created` `created` datetime(0) NOT NULL DEFAULT CURRENT_TIMESTAMP");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `role`");
        await queryRunner.query("ALTER TABLE `user` ADD `role` varchar(45) NULL");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `salt`");
        await queryRunner.query("ALTER TABLE `user` ADD `salt` varchar(16) NOT NULL");
        await queryRunner.query("ALTER TABLE `user` DROP COLUMN `profilePic`");
        await queryRunner.query("CREATE UNIQUE INDEX `token_UNIQUE` ON `pw_reset` (`token`)");
        await queryRunner.query("CREATE UNIQUE INDEX `userId_UNIQUE` ON `pw_reset` (`userId`)");
        await queryRunner.query("CREATE INDEX `lobby_game_fk_idx` ON `lobby` (`gameId`)");
        await queryRunner.query("CREATE INDEX `lobby_owner_fk_idx` ON `lobby` (`ownerId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `seat2Id_UNIQUE` ON `lobby` (`seat2Id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `seat1Id_UNIQUE` ON `lobby` (`seat1Id`)");
        await queryRunner.query("CREATE INDEX `winnerId_fk_idx` ON `game` (`winnerId`)");
        await queryRunner.query("CREATE INDEX `player2Id_fk_idx` ON `game` (`player2Id`)");
        await queryRunner.query("CREATE INDEX `player1Id_fk_idx` ON `game` (`player1Id`)");
        await queryRunner.query("CREATE UNIQUE INDEX `gameId_UNIQUE` ON `gamestate` (`gameId`)");
        await queryRunner.query("CREATE INDEX `playerId_fk_idx` ON `deck` (`playerId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `playerId_UNIQUE` ON `collection` (`playerId`)");
        await queryRunner.query("CREATE UNIQUE INDEX `email_UNIQUE` ON `user` (`email`)");
        await queryRunner.query("CREATE UNIQUE INDEX `username_UNIQUE` ON `user` (`username`)");
        await queryRunner.query("ALTER TABLE `pw_reset` ADD CONSTRAINT `pw_reset_user` FOREIGN KEY (`userId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `lobby` ADD CONSTRAINT `lobby_owner_fk` FOREIGN KEY (`ownerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `lobby` ADD CONSTRAINT `lobby_game_fk` FOREIGN KEY (`gameId`) REFERENCES `game`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `winnerId_fk` FOREIGN KEY (`winnerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `player2Id_fk` FOREIGN KEY (`player2Id`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `game` ADD CONSTRAINT `player1Id_fk` FOREIGN KEY (`player1Id`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `gamestate` ADD CONSTRAINT `gameId_fk` FOREIGN KEY (`gameId`) REFERENCES `game`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `deck` ADD CONSTRAINT `playerId_fk` FOREIGN KEY (`playerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
        await queryRunner.query("ALTER TABLE `collection` ADD CONSTRAINT `collectionPlayerId_fk` FOREIGN KEY (`playerId`) REFERENCES `user`(`id`) ON DELETE NO ACTION ON UPDATE NO ACTION");
    }

}
